services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - e=local
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"  # Lưu ý: ng serve chạy trên cổng 4200
    volumes:
      - ./frontend:/app  # Cho phép hot-reload
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096
    restart: unless-stopped